# Generated by Django 4.0.6 on 2022-07-29 01:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(6, 'Pin Code must have 6 digits')])),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(6, 'password must have minimum of 6 characters')])),
                ('date_of_birth', models.DateField(null=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('seperated', 'Seperated'), ('divorced', 'Divorced')], default='Single', max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Male', max_length=6)),
                ('aadhar_no', models.CharField(max_length=14, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(12, 'aadhar no must have 12 digits')])),
                ('business_name', models.CharField(max_length=100)),
                ('type_of_firm', models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('corporation', 'Corporation'), ('LLC', 'LLC')], default='Corporation', max_length=50)),
                ('sector', models.CharField(choices=[('healthcare', 'Healthcare'), ('finance', 'Finance'), ('automotive', 'Automotive'), ('telecommunications', 'Telecommunications'), ('food', 'Food'), ('construction', 'Construction'), ('manufacturing', 'Manufacturing'), ('mining', 'Mining'), ('energy', 'Energy'), ('chemical', 'Chemical'), ('aviation', 'Aviation'), ('information_Technology', 'Information Technology'), ('oil_&_gas', 'Oil & Gas'), ('public', 'Public'), ('others', 'Others')], default='Healthcare', max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('office_address', models.CharField(max_length=250)),
                ('GSTIN_No', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(10, 'GSTIN No must have minimum 10 characters')])),
                ('total_staff', models.IntegerField(null=True)),
                ('food_licence_no', models.CharField(max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(12, 'Food Licence No must have minimum 12 digits')])),
                ('official_website', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
