# Generated by Django 4.0.6 on 2022-07-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('martialstatus', models.CharField(max_length=20)),
                ('genter', models.CharField(max_length=20)),
                ('adhaarnum', models.IntegerField()),
                ('introdution', models.CharField(blank='no intro', max_length=40)),
            ],
        ),
    ]
